### ISSUE TITLE
autoConnectOnLogin doesn't work with the graalvm linux version

### ISSUE THREAD

**Issue by Xenapte** [rfresh2/ZenithProxy#113]
`autoConnectOnLogin` doesn't work with the linux version (with viaversion enabled). Connecting takes a long time and ends with the `Timed out waiting for the proxy to login` message. Even when I connect to the proxy server with my account already logged in it still takes ~15 seconds.

I've been reproducing this issue quite consistently on multiple server machines. So it's likely not a configuration problem. Maybe this is from some incompatibilities with graalvm? I don't see the same issue when using the java version.

### Error Logs

```
[2024/05/14 11:56:37] [Client] [INFO] Disconnected: io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@1e9756ef(incomplete)
[2024/05/14 11:56:37] [Client] [ERROR] 
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@1e9756ef(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:463)
	at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:159)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:248)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
	at org.geysermc.mcprotocollib.network.tcp.TcpClientSession.connect(TcpClientSession.java:102)
	at org.geysermc.mcprotocollib.network.tcp.TcpClientSession.connect(TcpClientSession.java:87)
	at com.zenith.network.client.ClientSession.connect(ClientSession.java:72)
	at com.zenith.Proxy.connect(Proxy.java:329)
	at com.zenith.Proxy.connect(Proxy.java:304)
	at com.zenith.network.server.handler.shared.outgoing.SGameProfileOutgoingHandler.apply(SGameProfileOutgoingHandler.java:46)
	at com.zenith.network.server.handler.shared.outgoing.SGameProfileOutgoingHandler.apply(SGameProfileOutgoingHandler.java:19)
	at com.zenith.network.registry.PacketHandlerStateCodec.handleOutgoing(PacketHandlerStateCodec.java:42)
	at com.zenith.network.registry.PacketHandlerCodec.handleOutgoing(PacketHandlerCodec.java:38)
	at com.zenith.network.registry.CodecRegistry.handleOutgoing(CodecRegistry.java:108)
	at com.zenith.network.server.ServerConnection.packetSending(ServerConnection.java:159)
	at org.geysermc.mcprotocollib.network.tcp.TcpSession.callPacketSending(TcpSession.java:168)
	at org.geysermc.mcprotocollib.network.tcp.TcpSession.send(TcpSession.java:343)
	at com.zenith.network.server.ServerConnection.send(ServerConnection.java:236)
	at com.zenith.network.server.handler.shared.postoutgoing.LoginCompressionPostOutgoingHandler.accept(LoginCompressionPostOutgoingHandler.java:15)
	at com.zenith.network.server.handler.shared.postoutgoing.LoginCompressionPostOutgoingHandler.accept(LoginCompressionPostOutgoingHandler.java:11)
	at com.zenith.network.registry.PostOutgoingPacketHandler.apply(PostOutgoingPacketHandler.java:10)
	at com.zenith.network.registry.PacketHandlerStateCodec.handlePostOutgoing(PacketHandlerStateCodec.java:50)
	at com.zenith.network.registry.PacketHandlerCodec.handlePostOutgoing(PacketHandlerCodec.java:42)
	at com.zenith.network.registry.CodecRegistry.handlePostOutgoing(CodecRegistry.java:119)
	at com.zenith.network.server.ServerConnection.packetSent(ServerConnection.java:170)
	at org.geysermc.mcprotocollib.network.tcp.TcpSession.callPacketSent(TcpSession.java:245)
	at org.geysermc.mcprotocollib.network.tcp.TcpSession.lambda$send$0(TcpSession.java:347)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:748)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:303)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:383)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:421)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:937)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1263)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
	at java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:853)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:829)
[2024/05/14 11:56:52] [Server] [INFO] Timed out waiting for the proxy to login
```

**Comment by rfresh2** [comment]
works fine for me

there's a few conditions it waits for before letting you login as seen here: https://github.com/rfresh2/ZenithProxy/blob/bc3eafb255c7a785c4cf57bdea67ab806b5df7b7/src/main/java/com/zenith/network/server/handler/shared/outgoing/SGameProfileOutgoingHandler.java#L51-L61

you haven't shared enough of your log for anyone to determine which of those is not being met so its difficult to say why its not working for you.

also please use the discord for support questions like this in the future
