### ISSUE TITLE
Permission denied when starting on Linux server

### ISSUE THREAD

**Issue by blurdn** [rfresh2/ZenithProxy#146]
I'm trying to host it on Linux server, but when I type ./launch I get Permission denied error
I understand I probably should change provider but is there any way to bypass it or run directly in bash console somehow?

**Comment by rfresh2** [comment]
`sudo chmod +x ./launch` 

then try again

**Comment by blurdn** [comment]
It worked, thanks! 
But I guess I still need to change provider, right? 
It says CRITICAL: Invalid system for release channel: java.1.21.0

**Comment by rfresh2** [comment]
You need java 21+ installed

**Comment by blurdn** [comment]
Yeah but it said Unsupported OS for linux release channel.
glibc version too low: 2.31
And also Java installation gives an error:

> Traceback (most recent call last):
  File "urllib/request.py", line 1344, in do_open
  File "http/client.py", line 1336, in request
  File "http/client.py", line 1382, in _send_request
  File "http/client.py", line 1331, in endheaders
  File "http/client.py", line 1091, in _send_output
  File "http/client.py", line 1035, in send
  File "http/client.py", line 1470, in connect
  File "http/client.py", line 1011, in connect
  File "http/client.py", line 979, in _tunnel
OSError: Tunnel connection failed: 403 Forbidden
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "jdk/__init__.py", line 100, in install
  File "jdk/client/client.py", line 53, in download
  File "urllib/request.py", line 215, in urlopen
  File "urllib/request.py", line 515, in open
  File "urllib/request.py", line 532, in _open
  File "urllib/request.py", line 492, in _call_chain
  File "urllib/request.py", line 1392, in https_open
  File "urllib/request.py", line 1347, in do_open
urllib.error.URLError: <urlopen error Tunnel connection failed: 403 Forbidden>
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "__main__.py", line 58, in <module>
  File "launch_platform.py", line 88, in validate_system_with_config
  File "launch_platform.py", line 73, in validate_java_system
  File "jdk_install.py", line 100, in get_java_executable
  File "jdk_install.py", line 88, in java_install_prompt
  File "jdk_install.py", line 40, in install_java
  File "jdk/__init__.py", line 105, in install
jdk.JdkError: <urlopen error Tunnel connection failed: 403 Forbidden>
[PYI-65:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by rfresh2** [comment]
You can ignore the linux release channel check log

You can install java yourself if the launcher is not able to. 

The instructions for how to do so will differ depending on your OS or linux distribution.

for example on ubuntu it'd be `sudo apt install openjdk-21-jdk`

**Comment by blurdn** [comment]
Oh my gosh, I think I'm going crazy with all of this
What I've figured out is that you can't use sudo and apt install on the free provider I'm using. Also you can't install Java manually because you can't upload files larger than 100 MiB.
So.. I really need to change the provider this time, don't I?

**Comment by rfresh2** [comment]
that would be the best decision, yes
