### ISSUE TITLE
Error on setting ChatRelay channel

### ISSUE THREAD

**Issue by blurdn** [rfresh2/ZenithProxy#147]
When I set ChatRelay channel using `chatrelay channel <channelID>` I get error:

>  chatrelay channel 1291853977784156200
[2024/10/05 18:35:02] [Terminal] [ERROR] Error while reading terminal input
java.lang.IllegalArgumentException: No such argument 'channel ID' exists on this command
        at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:102)
        at com.zenith.command.brigadier.CustomStringArgumentType.getString(CustomStringArgumentType.java:27)
        at com.zenith.command.impl.ChatRelayCommand.lambda$register$2(ChatRelayCommand.java:76)
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
        at com.mojang.brigadier.context.ContextChain.executeAll(ContextChain.java:88)
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:228)
        at com.zenith.command.CommandManager.executeWithHandlers(CommandManager.java:183)
        at com.zenith.command.CommandManager.execute(CommandManager.java:132)
        at com.zenith.command.CommandManager.execute(CommandManager.java:143)
        at com.zenith.terminal.TerminalManager.executeDiscordCommand(TerminalManager.java:87)
        at com.zenith.terminal.TerminalManager.handleTerminalCommand(TerminalManager.java:81)
        at com.zenith.terminal.TerminalManager.lambda$new$1(TerminalManager.java:62)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by blurdn** [comment]
used `./launch --setup` for setting channel
