### ISSUE TITLE
Some servers completely break the proxy

### ISSUE THREAD

**Issue by Quadragintillion** [rfresh2/ZenithProxy#77]
Not exactly sure what's causing this, but on certain servers the console is flooded with error messages ("[Client] [ERROR] Error writing chunk cache") and almost every message is replaced with %s.

One of the servers affected by this is event.pdl.is (though it's only running at certain times)

**Comment by rfresh2** [comment]
Post your logs here. Hard to say what's going on without them.

No guarantees its something that can be resolved though. This software is designed for vanilla servers, not modded servers or servers with custom resource packs.

**Comment by Quadragintillion** [comment]
```[2024/01/09 00:27:40] [Terminal] [INFO]
Terminal Command Executed
c
[2024/01/09 00:27:40] [Terminal] [INFO] ^[[38;5;163m
Connecting...^[[0m
[2024/01/09 00:27:40] [Auth] [INFO] Logging in DraginCraft...
[2024/01/09 00:27:41] [Auth] [INFO] Logged in as DraginCraft [8b0459f7-648b-4cc2-b04d-caed86f29981].
[2024/01/09 00:27:41] [Client] [INFO] Connecting to event.pdl.is:25565...
[2024/01/09 00:27:41] [Client] [INFO] Updating detected protocol version 765 for server: event.pdl.is:25565
[2024/01/09 00:27:41] [Proxy] [ERROR] Error initializing ViaBackwards
java.lang.NullPointerException: null
        at com.viaversion.viaversion.ViaManagerImpl.addEnableListener(ViaManagerImpl.java:332)
        at com.zenith.via.platform.ZViaBackwardsPlatform.initViaBackwards(ZViaBackwardsPlatform.java:20)
        at com.zenith.via.ZViaServerProxyPlatform.init(ZViaServerProxyPlatform.java:57)
        at com.zenith.Proxy.connect(Proxy.java:310)
        at com.zenith.Proxy.connectAndCatchExceptions(Proxy.java:262)
        at java.base@21.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
[2024/01/09 00:27:41] [Client] [INFO] Connected to event.pdl.is/31.25.11.73:25565!
[2024/01/09 00:27:41] [Terminal] [INFO] ^[[38;5;163m
Proxy Connected
Server: event.pdl.is
Proxy IP: 18.215.193.60:26734^[[0m
[2024/01/09 00:27:42] [Terminal] [INFO] ^[[38;5;25m
Proxy Online^[[0m
[2024/01/09 00:27:42] [Chat] [INFO] Hey DraginCraft!
Join the stream: https://twitch.tv/pdlbackup
[2024/01/09 00:27:42] [Client] [ERROR] Error writing chunk cache
java.lang.IndexOutOfBoundsException: readerIndex(13967) + length(2) exceeds writerIndex(13967): UnpooledHeapByteBuf(ridx: 13967, widx: 13967, cap: 13967/13967)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
        at com.zenith.cache.data.chunk.ChunkCache.readChunkSection(ChunkCache.java:455)
        at com.zenith.cache.data.chunk.ChunkCache.lambda$add$16(ChunkCache.java:443)
        at com.zenith.cache.data.chunk.ChunkCache.writeCache(ChunkCache.java:330)
        at com.zenith.cache.data.chunk.ChunkCache.add(ChunkCache.java:421)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:13)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:10)
        at com.zenith.network.registry.AsyncPacketHandler.applyWithRetries(AsyncPacketHandler.java:23)
        at com.zenith.network.registry.AsyncPacketHandler.lambda$apply$0(AsyncPacketHandler.java:16)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
[2024/01/09 00:27:42] [Client] [ERROR] Error writing chunk cache
java.lang.IndexOutOfBoundsException: readerIndex(19556) + length(2) exceeds writerIndex(19556): UnpooledHeapByteBuf(ridx: 19556, widx: 19556, cap: 19556/19556)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
        at com.zenith.cache.data.chunk.ChunkCache.readChunkSection(ChunkCache.java:455)
        at com.zenith.cache.data.chunk.ChunkCache.lambda$add$16(ChunkCache.java:443)
        at com.zenith.cache.data.chunk.ChunkCache.writeCache(ChunkCache.java:330)
        at com.zenith.cache.data.chunk.ChunkCache.add(ChunkCache.java:421)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:13)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:10)
        at com.zenith.network.registry.AsyncPacketHandler.applyWithRetries(AsyncPacketHandler.java:23)
        at com.zenith.network.registry.AsyncPacketHandler.lambda$apply$0(AsyncPacketHandler.java:16)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
[2024/01/09 00:27:42] [Client] [ERROR] Error writing chunk cache
java.lang.IndexOutOfBoundsException: readerIndex(18158) + length(2) exceeds writerIndex(18158): UnpooledHeapByteBuf(ridx: 18158, widx: 18158, cap: 18158/18158)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
        at com.zenith.cache.data.chunk.ChunkCache.readChunkSection(ChunkCache.java:455)
        at com.zenith.cache.data.chunk.ChunkCache.lambda$add$16(ChunkCache.java:443)
        at com.zenith.cache.data.chunk.ChunkCache.writeCache(ChunkCache.java:330)
        at com.zenith.cache.data.chunk.ChunkCache.add(ChunkCache.java:421)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:13)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:10)
        at com.zenith.network.registry.AsyncPacketHandler.applyWithRetries(AsyncPacketHandler.java:23)
        at com.zenith.network.registry.AsyncPacketHandler.lambda$apply$0(AsyncPacketHandler.java:16)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
[2024/01/09 00:27:42] [Client] [ERROR] Error writing chunk cache
java.lang.IndexOutOfBoundsException: readerIndex(13994) + length(2) exceeds writerIndex(13994): UnpooledHeapByteBuf(ridx: 13994, widx: 13994, cap: 13994/13994)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
        at com.zenith.cache.data.chunk.ChunkCache.readChunkSection(ChunkCache.java:455)
        at com.zenith.cache.data.chunk.ChunkCache.lambda$add$16(ChunkCache.java:443)
        at com.zenith.cache.data.chunk.ChunkCache.writeCache(ChunkCache.java:330)
        at com.zenith.cache.data.chunk.ChunkCache.add(ChunkCache.java:421)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:13)
        at com.zenith.network.client.handler.incoming.level.LevelChunkWithLightHandler.applyAsync(LevelChunkWithLightHandler.java:10)
        at com.zenith.network.registry.AsyncPacketHandler.applyWithRetries(AsyncPacketHandler.java:23)
        at com.zenith.network.registry.AsyncPacketHandler.lambda$apply$0(AsyncPacketHandler.java:16)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```
... a bunch of the same error message ...

```
[2024/01/09 00:27:44] [Terminal] [INFO]
Terminal Command Executed
dc
[2024/01/09 00:27:44] [Client] [INFO] Disconnecting from server...
[2024/01/09 00:27:44] [Client] [INFO] Disconnected: Manual Disconnect
[2024/01/09 00:27:44] [Terminal] [INFO]
[2024/01/09 00:27:44] [Terminal] [INFO] ^[[38;5;166m
Proxy Disconnected
Reason: Manual Disconnect
Online Duration: 2s^[[0m
[2024/01/09 00:27:48] [Terminal] [INFO]
Terminal Command Executed
via
[2024/01/09 00:27:48] [Terminal] [INFO] ^[[38;5;166m
Invalid command usage
ViaVersion: on
AutoConfig: on
Version: 1.20.3/1.20.4
Usage: Configure ViaVersion
  via on/off
  via autoConfig on/off
  via version <MC version>^[[0m
[2024/01/09 00:27:55] [Terminal] [INFO]
Terminal Command Executed
via version 1.20.4
[2024/01/09 00:27:55] [Terminal] [INFO] ^[[38;5;51m
ViaVersion Version Updated!
ViaVersion: on
AutoConfig: on
Version: 1.20.3/1.20.4^[[0m
[2024/01/09 00:27:57] [Terminal] [INFO]
Terminal Command Executed
c
[2024/01/09 00:27:57] [Auth] [INFO] Logging in DraginCraft...
[2024/01/09 00:27:57] [Terminal] [INFO] ^[[38;5;163m
Connecting...^[[0m
[2024/01/09 00:27:58] [Auth] [INFO] Logged in as DraginCraft [8b0459f7-648b-4cc2-b04d-caed86f29981].
[2024/01/09 00:27:58] [Client] [INFO] Connecting to event.pdl.is:25565...
[2024/01/09 00:27:58] [Client] [INFO] Updating detected protocol version 765 for server: event.pdl.is:25565
[2024/01/09 00:27:58] [Proxy] [ERROR] Error initializing ViaBackwards
java.lang.NullPointerException: null
        at com.viaversion.viaversion.ViaManagerImpl.addEnableListener(ViaManagerImpl.java:332)
        at com.zenith.via.platform.ZViaBackwardsPlatform.initViaBackwards(ZViaBackwardsPlatform.java:20)
        at com.zenith.via.ZViaServerProxyPlatform.init(ZViaServerProxyPlatform.java:57)
        at com.zenith.Proxy.connect(Proxy.java:310)
        at com.zenith.Proxy.connectAndCatchExceptions(Proxy.java:262)
        at java.base@21.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
[2024/01/09 00:27:58] [Client] [INFO] Connected to event.pdl.is/31.25.11.73:25565!
[2024/01/09 00:27:58] [Terminal] [INFO] ^[[38;5;163m
Proxy Connected
Server: event.pdl.is
Proxy IP: 18.215.193.60:26734^[[0m
[2024/01/09 00:27:59] [Terminal] [INFO] ^[[38;5;25m
Proxy Online^[[0m
[2024/01/09 00:27:59] [Chat] [INFO] Hey DraginCraft!
Join the stream: https://twitch.tv/pdlbackup
```
... more chunk cache errors ...
```
[2024/01/09 00:28:09] [Chat] [INFO] %s
[2024/01/09 00:28:12] [Chat] [INFO] %s
[2024/01/09 00:28:13] [Chat] [INFO] %s
[2024/01/09 00:28:16] [Chat] [INFO] %s
[2024/01/09 00:28:19] [Chat] [INFO] %s
[2024/01/09 00:28:27] [Chat] [INFO] Luke0928 died
[2024/01/09 00:28:31] [Chat] [INFO] Astrickz died
[2024/01/09 00:28:37] [Chat] [INFO] %s
[2024/01/09 00:28:38] [Chat] [INFO] %s
[2024/01/09 00:28:40] [Chat] [INFO] skeppys_cream died
[2024/01/09 00:28:42] [Chat] [INFO] 2suf died
[2024/01/09 00:29:03] [Chat] [INFO] %s
[2024/01/09 00:29:12] [Chat] [INFO] %s
[2024/01/09 00:29:13] [Chat] [INFO] %s
[2024/01/09 00:29:25] [Chat] [INFO] %s
[2024/01/09 00:29:26] [Chat] [INFO] 2suf died
[2024/01/09 00:29:33] [Chat] [INFO] %s
[2024/01/09 00:29:38] [Chat] [INFO] Astrickz died
[2024/01/09 00:29:40] [Chat] [INFO] %s
[2024/01/09 00:29:43] [Chat] [INFO] Ducketic died
[2024/01/09 00:29:44] [Chat] [INFO] %s
[2024/01/09 00:29:44] [Chat] [INFO] %s
[2024/01/09 00:29:48] [Chat] [INFO] Astrickz died
[2024/01/09 00:29:49] [Chat] [INFO] %s
[2024/01/09 00:29:50] [Chat] [INFO] %s
[2024/01/09 00:29:55] [Chat] [INFO] skidlol died
[2024/01/09 00:30:03] [Chat] [INFO] ⏺ LIVE! Join the stream: twitch.tv/pdlbackup
[2024/01/09 00:30:09] [Chat] [INFO] 2suf died
[2024/01/09 00:30:15] [Chat] [INFO] %s
[2024/01/09 00:30:15] [Chat] [INFO] %s
[2024/01/09 00:30:16] [Chat] [INFO] skidlol died
[2024/01/09 00:30:16] [Chat] [INFO] %s
[2024/01/09 00:30:16] [Chat] [INFO] %s
[2024/01/09 00:30:17] [Chat] [INFO] %s
[2024/01/09 00:30:18] [Chat] [INFO] %s
[2024/01/09 00:30:20] [Chat] [INFO] %s
[2024/01/09 00:30:24] [Chat] [INFO] %s
[2024/01/09 00:30:24] [Chat] [INFO] skeppys_cream died
[2024/01/09 00:30:25] [Chat] [INFO] %s
[2024/01/09 00:30:25] [Chat] [INFO] pdl died
[2024/01/09 00:30:26] [Chat] [INFO] Astrickz died
[2024/01/09 00:30:27] [Chat] [INFO] %s
[2024/01/09 00:30:34] [Chat] [INFO] skeppy6d died
[2024/01/09 00:30:35] [Chat] [INFO] Astrickz died
[2024/01/09 00:30:41] [Chat] [INFO] %s
[2024/01/09 00:30:42] [Chat] [INFO] %s
[2024/01/09 00:30:45] [Chat] [INFO] %s
[2024/01/09 00:30:45] [Chat] [INFO] skidlol died
[2024/01/09 00:30:47] [Chat] [INFO] %s
[2024/01/09 00:30:47] [Chat] [INFO] %s
[2024/01/09 00:30:49] [Chat] [INFO] %s
[2024/01/09 00:30:53] [Chat] [INFO] %s
[2024/01/09 00:30:55] [Chat] [INFO] %s
[2024/01/09 00:30:56] [Chat] [INFO] tutorialhow2sit died
[2024/01/09 00:30:58] [Chat] [INFO] Luke0928 died
```

**Comment by rfresh2** [comment]
Can u run the status command and show what version of zenith ur on?

There was an issue with via backwards initialization that looks exactly like this but was fixed weeks ago

**Comment by Quadragintillion** [comment]
ZenithProxy 2.6.2+linux.1.20.1 Status: DraginCraft
Status: Online
Connected User: None
Online Time: 16:24:38
Proxy IP: [removed]
Server: play.invadedlands.net:25565
Priority Queue: no [unbanned]
TPS: 19.98
2b2t Queue: Priority: 1 [00:00:12]
Regular: 254 [04:13:25]
Dimension: overworld
Coordinates: ||[-41, 69, 81]||
Health: 18.1144
AutoDisconnect: [Health: off (5)]
[CancelAutoReconnect: off]
[AutoClientDisconnect: off]
[Thunder: off]
AutoReconnect: on [5]
AutoRespawn: on [100]
AntiAFK: on
AutoEat: on
VisualRange Notifications: off
[Mention: on]
Client Connection Notifications: on
Stalk: on
Spectators: off
[Public Chat: on]
Active Hours: off
Chat Relay: on
[WhisperMention: on]
[NameMention: on]
AutoReply: off
[Cooldown: 15]
Spammer: off
[Whisper: off]
AutoUpdate: on

**Comment by Quadragintillion** [comment]
> Can u run the status command and show what version of zenith ur on?
> 
> There was an issue with via backwards initialization that looks exactly like this but was fixed weeks ago

Also, if you look further down in my log, I turned off via backwards and still had the issue.

**Comment by Quadragintillion** [comment]
This can be reproduced right now on play.invadedlands.net (join event-b and you will be spammed with the error) which is weird because the event-b server seems to be completely vanilla

**Comment by Quadragintillion** [comment]
I'm also being spammed with
```
[2024/01/09 20:18:20] [Client] [ERROR] Async handler error
java.lang.NullPointerException: null
        at com.zenith.cache.data.chunk.ChunkCache.updateBlock(ChunkCache.java:153)
        at com.zenith.cache.data.chunk.ChunkCache.updateBlock(ChunkCache.java:280)
        at com.zenith.network.client.handler.incoming.level.BlockUpdateHandler.applyAsync(BlockUpdateHandler.java:14)
        at com.zenith.network.client.handler.incoming.level.BlockUpdateHandler.applyAsync(BlockUpdateHandler.java:10)
        at com.zenith.network.registry.AsyncPacketHandler.applyWithRetries(AsyncPacketHandler.java:23)
        at com.zenith.network.registry.AsyncPacketHandler.lambda$apply$0(AsyncPacketHandler.java:16)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

**Comment by rfresh2** [comment]
ViaBackwards exceptions resolved by https://github.com/rfresh2/ZenithProxy/commit/32ccd7f0f1a7a2c2d9d5a0e20c86539da34963a0

Empty chunk section reads resolved by https://github.com/rfresh2/ZenithProxy/commit/ec24c0a99bf6cebaf54fbefb9bac4320fbfb0fe8

Chat %s msgs might be due to a language resource pack provided by the server, not sure

**Comment by Quadragintillion** [comment]
Not using any resource packs. Maybe the chat being formatted like USERNAME: MESSAGE instead of <USERNAME> MESSAGE is breaking it?
Edit: no wait, it worked fine for the same server before, this only actually started happening after the errors appeared.

**Comment by rfresh2** [comment]
The reason i'm thinking language packs is its common for these to be sent during the login phase. It wouldn't necessarily be something you manually download yourself as a player.

Here's a snippet of the bundled vanilla mc language pack that zenith uses
![idea64_jTBHq7ZjWu](https://github.com/rfresh2/ZenithProxy/assets/89827146/6c10fbbd-606d-4855-835f-f2004b0c9bd3)

you can see the %s formatting is standard in these.

the possible incompatibility is that zenith doesn't update or modify its language pack based on anything the server sends.

**Comment by Quadragintillion** [comment]
It could be that the errors causes something to return early and therefore ignore it?
I think it should be fine for now though. Can you make a release with the new patch?

**Comment by rfresh2** [comment]
Closing this as most has been resolved and discussion of further stuff moved to discord
